# Generated by Django 5.1.3 on 2024-11-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='contrasena',
            field=models.CharField(max_length=255),
        ),
    ]
