# Generated by Django 5.0.4 on 2024-11-20 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='propiedad',
            table='propiedades',
        ),
    ]
