# Generated by Django 5.0.4 on 2024-11-20 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_propiedad_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='oferta',
            table='ofertas',
        ),
        migrations.AlterModelTable(
            name='usuario',
            table='usuarios',
        ),
    ]
