# Generated by Django 5.1.3 on 2024-11-28 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_propiedad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('descripcion', models.TextField(default='La oferta se cerrará dentro de poco')),
                ('precio_ofrecido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado_oferta', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20)),
                ('fecha_oferta', models.DateTimeField(auto_now_add=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='core.propiedad')),
            ],
            options={
                'db_table': 'ofertas',
            },
        ),
    ]
