# Generated by Django 5.0.4 on 2024-11-20 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_oferta_table_alter_usuario_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oferta',
            name='usuario',
        ),
        migrations.AddField(
            model_name='oferta',
            name='descripcion',
            field=models.TextField(default='La oferta se cerrará dentro de poco'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='estado_oferta',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='precio_ofrecido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='core.propiedad'),
        ),
    ]
