# Generated by Django 5.0.4 on 2024-11-20 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_oferta_usuario_oferta_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usuario'),
        ),
    ]
