# Generated by Django 5.1.3 on 2024-12-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mensaje_visto'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='fecha_expiracion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
