# Generated by Django 5.1.3 on 2024-12-02 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mensaje_visto'),
        ('moduloac', '0002_alter_fotoadicional_url_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversacion',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloac.propiedad'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='moduloac.propiedad'),
        ),
        migrations.DeleteModel(
            name='Propiedad',
        ),
    ]
