# Generated by Django 5.1.3 on 2024-12-02 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_favorito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Cambio de precio', 'Cambio de precio'), ('Cambio de oferta', 'Cambio de oferta'), ('Vencimiento de oferta', 'Vencimiento de oferta'), ('Cambio de disponibilidad', 'Cambio de disponibilidad'), ('Guardado en favoritos', 'Guardado en favoritos')], max_length=50)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.propiedad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notificaciones',
            },
        ),
    ]
