# Generated by Django 5.1.3 on 2024-11-15 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=191)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto_frontal', models.TextField(blank=True, null=True)),
                ('disponibilidad', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(blank=True, max_length=191, null=True)),
                ('tamano_m2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('fecha_venta', models.DateField(blank=True, null=True)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('eliminado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propiedades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FotoAdicional',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url_foto', models.TextField()),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_adicionales', to='moduloac.propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='ClasificacionPropiedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(choices=[('Urbana', 'Urbana'), ('Rural', 'Rural'), ('En Fraccionamiento', 'En Fraccionamiento')], max_length=20)),
                ('estado_propiedad', models.CharField(choices=[('En negociación', 'En negociación'), ('Negociada', 'Negociada'), ('En espera', 'En espera'), ('Cancelada', 'Cancelada'), ('Activa', 'Activa')], max_length=20)),
                ('privada', models.CharField(blank=True, choices=[('Cerrada', 'Cerrada'), ('Abierta', 'Abierta'), ('No Aplica', 'No aplica')], max_length=20, null=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificacion', to='moduloac.propiedad')),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('electricidad', models.BooleanField(default=False)),
                ('agua', models.BooleanField(default=False)),
                ('gas', models.BooleanField(default=False)),
                ('internet', models.BooleanField(default=False)),
                ('television_cable', models.BooleanField(default=False)),
                ('aire_acondicionado', models.BooleanField(default=False)),
                ('calefaccion', models.BooleanField(default=False)),
                ('cocina_equipada', models.BooleanField(default=False)),
                ('closets_empotrados', models.BooleanField(default=False)),
                ('jardin_privado', models.BooleanField(default=False)),
                ('patio_privado', models.BooleanField(default=False)),
                ('terraza', models.BooleanField(default=False)),
                ('balcon', models.BooleanField(default=False)),
                ('piscina', models.BooleanField(default=False)),
                ('jacuzzi', models.BooleanField(default=False)),
                ('camaras_vigilancia', models.BooleanField(default=False)),
                ('alarmas', models.BooleanField(default=False)),
                ('cercas_electricas', models.BooleanField(default=False)),
                ('acceso_controlado', models.BooleanField(default=False)),
                ('domotica', models.BooleanField(default=False)),
                ('automatizacion_luces', models.BooleanField(default=False)),
                ('cerraduras_inteligentes', models.BooleanField(default=False)),
                ('termostato_inteligente', models.BooleanField(default=False)),
                ('oficina_en_casa', models.BooleanField(default=False)),
                ('estacionamiento_cubierto', models.BooleanField(default=False)),
                ('cochera', models.BooleanField(default=False)),
                ('cuarto_servicio', models.BooleanField(default=False)),
                ('lavadero', models.BooleanField(default=False)),
                ('bodega', models.BooleanField(default=False)),
                ('seguridad_24_7', models.BooleanField(default=False)),
                ('areas_verdes_comunes', models.BooleanField(default=False)),
                ('jardines', models.BooleanField(default=False)),
                ('zona_juegos_infantiles', models.BooleanField(default=False)),
                ('gimnasio', models.BooleanField(default=False)),
                ('area_deportiva', models.BooleanField(default=False)),
                ('paneles_solares', models.BooleanField(default=False)),
                ('cisterna', models.BooleanField(default=False)),
                ('captacion_agua_lluvia', models.BooleanField(default=False)),
                ('ventanas_doble_vidrio', models.BooleanField(default=False)),
                ('aislamiento_termico', models.BooleanField(default=False)),
                ('jardines_verticales', models.BooleanField(default=False)),
                ('propiedad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='moduloac.propiedad')),
            ],
        ),
    ]
