# Generated by Django 5.1.3 on 2024-11-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoadicional',
            name='url_foto',
            field=models.ImageField(upload_to='propiedades/fotos_adicionales/'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='foto_frontal',
            field=models.ImageField(blank=True, null=True, upload_to='propiedades/fotos_frontal/'),
        ),
    ]
