# Generated by Django 5.1.3 on 2024-12-03 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloac', '0002_alter_fotoadicional_url_foto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propiedad',
            old_name='tamano_m2',
            new_name='tamano_m2_const',
        ),
        migrations.RemoveField(
            model_name='propiedad',
            name='disponibilidad',
        ),
        migrations.AddField(
            model_name='propiedad',
            name='tamano_m2_terr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
