# Generated by Django 5.0.6 on 2024-11-22 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('ingreso_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plazo_meses', models.IntegerField()),
                ('mensualidad', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('monto_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
